# Generated by Django 5.1.3 on 2025-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
